services:

  # -------------------------
  # LLM (local inference)
  # -------------------------
  ollama:
    image: ollama/ollama
    deploy:
      resources:
        limits:
           memory: 6G

    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_LOAD_TIMEOUT=10m
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_KEEP_ALIVE=60m

  # -------------------------
  # GRAPH MEMORY (Neo4j)
  # -------------------------
  neo4j:
    image: neo4j:5.15
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 7687 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # -------------------------
  # LANGFUSE (observability)
  # -------------------------
  langfuse:
    image: langfuse/langfuse:2
    container_name: langfuse
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@langfuse-db:5432/langfuse
      - NEXTAUTH_SECRET=secret
      - NEXTAUTH_URL=http://localhost:3000
      - SALT=secret
    depends_on:
      - langfuse-db

  langfuse-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: langfuse
    volumes:
      - langfuse_db:/var/lib/postgresql/data

  # -------------------------
  # AGENT SYSTEM (your code)
  # -------------------------
  agent-system:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: agent_system

    volumes:
      - ../:/app

    environment:
      - OLLAMA_HOST=http://ollama:11434
      - NEO4J_URI=bolt://neo4j:7687
      - LANGFUSE_HOST=http://langfuse:3000
      - LANGFUSE_SECRET_KEY=xxx
      - LANGFUSE_PUBLIC_KEY=xxx
      - LLM_URL=http://ollama:11434/api/generate

    depends_on:
      ollama:
        condition: service_started
      neo4j:
        condition: service_started
      langfuse:
        condition: service_started

volumes:
  ollama_data:
  neo4j_data:
  langfuse_db: